// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:simple_note_app/core/init/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingModelAdapter());
    registerAdapter(NoteModelAdapter());
    registerAdapter(NoteOrderAdapter());
  }
}
